create table INVOICE (
	INV_NUM char(5) primary key,
    CUST_ID int,
    EMP_ID char(5),
    PART_NUM int,
    PARTQTY int,
    FOREIGN KEY (PART_NUM) REFERENCES PART(PART_NUM),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

